export const BList = [
  // 아무 것도 아닐 때 green 모든 과정 완료 black
  // 표지 전자 업로드 2
  {
    id: "001",
    name: "서근재",
    storyId: 6,
    phone: "010-1234-1178",
    nickname: "아따힘들다",
    address: "서울시 어디구 어디동",
    coupon: "ARFESE1212",
    pakage: "꿈2",
    status: "2/14",
    answer: "바로가기",
    sign: "표지",
    electron: "전자",
    done: "O",
  },
  {
    id: "002",
    name: "근재",
    storyId: 7,
    phone: "010-1234-5668",
    nickname: "아땃힘들다",
    address: "서울시 어디구 어디동",
    coupon: "ARFESE1212",
    pakage: "사랑3",
    status: "6/7",
    answer: "바로가기",
    sign: "표지",
    electron: "전자",
    done: "2",
  },
  {
    id: "003",
    name: "재근",
    storyId: 6,
    phone: "010-1224-5678",
    nickname: "아땅힘들다",
    address: "서울시 어디구 어디동",
    coupon: "ARFESE1212",
    pakage: "감정1",
    status: "제출",
    answer: "바로가기",
    sign: "표지",
    electron: "전자",
    done: "not",
  },
  {
    id: "004",
    name: "서재",
    storyId: 6,
    phone: "010-1034-5678",
    nickname: "아띠힘들다",
    address: "서울시 어디구 어디동",
    coupon: "ARFESE1212",
    pakage: "행복3",
    status: "배송",
    answer: "바로가기",
    sign: "표지",
    electron: "전자",
    done: "",
  },
  {
    id: "005",
    name: "서재근",
    storyId: 6,
    phone: "010-1234-5677",
    nickname: "하따힘들다",
    address: "서울시 어디구 어디동",
    coupon: "ARFESE1212",
    pakage: "꿈2",
    status: "완료",
    answer: "바로가기",
    sign: "표지",
    electron: "전자",
    done: "O",
  },
  {
    id: "006",
    name: "서감자",
    storyId: 6,
    phone: "010-1232-5678",
    nickname: "이따힘들다",
    address: "서울시 어디구 어디동",
    coupon: "ARFESE1212",
    pakage: "꿈2",
    status: "2/14",
    answer: "바로가기",
    sign: "표지",
    electron: "전자",
    done: "",
  },
  {
    id: "007",
    name: "서근재",
    storyId: 6,
    phone: "010-1234-5678",
    nickname: "아따힘들다",
    address: "서울시 어디구 어디동",
    coupon: "ARFESE1212",
    pakage: "꿈2",
    status: "2/14",
    answer: "바로가기",
    sign: "표지",
    electron: "전자",
    done: "",
    img: "./src/assets/get_up_and_coding.jpg",
    people_answer: "사용자 답벼어어언",
    ai_answer: "ai 답벼어어언",
  },
  {
    id: "008",
    name: "서근재",
    storyId: 6,
    phone: "010-1234-5678",
    nickname: "아따힘들다",
    address: "서울시 어디구 어디동",
    coupon: "ARFESE1212",
    pakage: "꿈2",
    status: "2/14",
    answer: "바로가기",
    sign: "표지",
    electron: "전자",
    done: "",
    img: "./src/assets/get_up_and_coding.jpg",
    people_answer: "사용자 답벼어어언",
    ai_answer: "ai 답벼어어언",
  },
  // {
  //   id: "009",
  //   name: "서근재",
  //   storyId: 6,
  //   phone: "010-1234-5678",
  //   nickname: "아따힘들다",
  //   address: "서울시 어디구 어디동",
  //   coupon: "ARFESE1212",
  //   pakage: "꿈2",
  //   status: "2/14",
  //   answer: "바로가기",
  //   sign: "표지",
  //   electron: "전자",
  //   done: "",
  //   img: "./src/assets/get_up_and_coding.jpg",
  //   people_answer: "사용자 답벼어어언",
  //   ai_answer: "ai 답벼어어언",
  // },
  // {
  //   id: "010",
  //   name: "서근재",
  //   storyId: 6,
  //   phone: "010-1234-5678",
  //   nickname: "아따힘들다",
  //   address: "서울시 어디구 어디동",
  //   coupon: "ARFESE1212",
  //   pakage: "꿈2",
  //   status: "2/14",
  //   answer: "바로가기",
  //   sign: "표지",
  //   electron: "전자",
  //   done: "",
  //   img: "./src/assets/get_up_and_coding.jpg",
  //   people_answer: "사용자 답벼어어언",
  //   ai_answer: "ai 답벼어어언",
  // },
  // {
  //   id: "011",
  //   name: "서근재",
  //   storyId: 6,
  //   phone: "010-1234-5678",
  //   nickname: "아따힘들다",
  //   address: "서울시 어디구 어디동",
  //   coupon: "ARFESE1212",
  //   pakage: "꿈2",
  //   status: "2/14",
  //   answer: "바로가기",
  //   sign: "표지",
  //   electron: "전자",
  //   done: "",
  //   img: "./src/assets/get_up_and_coding.jpg",
  //   people_answer: "사용자 답벼어어언",
  //   ai_answer: "ai 답벼어어언",
  // },
  // {
  //   id: "012",
  //   name: "서근재",
  //   storyId: 6,
  //   phone: "010-1234-5678",
  //   nickname: "아따힘들다",
  //   address: "서울시 어디구 어디동",
  //   coupon: "ARFESE1212",
  //   pakage: "꿈2",
  //   status: "2/14",
  //   answer: "바로가기",
  //   sign: "표지",
  //   electron: "전자",
  //   done: "",
  //   img: "./src/assets/get_up_and_coding.jpg",
  //   people_answer: "사용자 답벼어어언",
  //   ai_answer: "ai 답벼어어언",
  // },
];
