export const BList = [
  // 아무 것도 아닐 때 green 모든 과정 완료 black
  // 표지 전자 업로드 2
  {
    address: "  ",
    answerCount: 2,
    couponNumber: "1127",
    imgStatus: false,
    name: "당신의 감정을 담아내다",
    option: "실물책",
    phone: "최종 제출 전",
    questionCount: 7,
    userEmail: "heos2jin@gmail.com",
    userId: 1618,
    userName: "최종 제출 전",
    userNickname: "1",
    userSubscribeStory: 53,
  },
  {
    address: "15811 경기도 군포시 금정로임 ㅋ",
    answerCount: 4,
    couponNumber: "1131",
    imgStatus: true,
    name: "당신의 감정을 담아내다",
    option: "실물책",
    phone: "01041361005",
    questionCount: 7,
    userEmail: "dongheon9265@kakao.com",
    userId: 1636,
    userName: "김동헌",
    userNickname: "Heon",
    userSubscribeStory: 95,
  },
  {
    address: "  ",
    answerCount: 1,
    couponNumber: "1132",
    imgStatus: false,
    name: "test",
    option: "전자책",
    phone: "최종 제출 전",
    questionCount: 2,
    userEmail: "dongheon9265@kakao.com",
    userId: 1636,
    userName: "최종 제출 전",
    userNickname: "Heon",
    userSubscribeStory: 96,
  },
];
