export const BList = [
  // 아무 것도 아닐 때 green 모든 과정 완료 black
  // 표지 전자 업로드 2
  {
    userAddress: "인천광역시 어디구 어디로",
    answerCount: 2,
    couponNumber: "1127",
    imgStatus: false,
    name: "당신의 감정을 담아내다",
    option: "실물책",
    userPhoneNumber: "010-1234-5678",
    questionCount: 7,
    userEmail: "heos2jin@gmail.com",
    userId: 1618,
    userName: "동헌김",
    userNickname: "1",
    userSubscribeStory: 53,
    imgLink: "src/assets/get_up_and_coding.jpg",
    answers: [
      [
        "사람이 살다보면 그런 마음이 들때가 있는 법이죠.",
        "하지만 그럼에도 꿋꿋히 나아가는 당신이 멋집니다. ",
      ],
      [
        "그렇군요! 저는 당신에게 공감하지는 못하지만 당신은 아주 멋지다고 말씀을 드리고 싶어요!",
        "당신은 항상 옳고 올바르게 나아가고 있음을 느끼셨으면 좋겠습니다!",
      ],
      ["나는 행복합니다.", "나는 아주 행복합니다."],
    ],
  },
  {
    userAddress: "15811 경기도 군포시 금정로임 ㅋ",
    answerCount: 4,
    couponNumber: "1131",
    imgStatus: true,
    name: "당신의 감정을 담아내다",
    option: "실물책",
    userPhoneNumber: "010-4136-1005",
    questionCount: 7,
    userEmail: "dongheon9265@kakao.com",
    userId: 1636,
    userName: "김동헌",
    userNickname: "Heon",
    userSubscribeStory: 95,
    imgLink: "src/assets/images/testImg1.jpg",
    answers: [
      {
        people_answer:
          "항상 좋은 일만은 있을 순 없지요. 그럼에도 인생사 새옹지마 그런 일이 있어도 항상 나아가는 당신은 멋진 사람이에요",
        ai_answer:
          "여기에서 교훈을 얻을 수 있습니다. 운은 항상 준비된 자에게 오고 그걸 잡는건 당신의 준비성이라고. 그러므로 당신에게 행운을 빕니다.",
        etc: ["나는 행복합니다아아아.", "나는 아주아주  행복합니다."],
      },
    ],
  },
  {
    userAddress: "서울시 어디구 어디로",
    answerCount: 6,
    couponNumber: "1132",
    imgStatus: false,
    name: "test",
    option: "전자책",
    userPhoneNumber: "010-1234-5666",
    questionCount: 14,
    userEmail: "dongheon9265@kakao.com",
    userId: 1632,
    userName: "서재",
    userNickname: "Heon",
    userSubscribeStory: 94,
    imgLink: "src/assets/images/testImg2.jpg",
  },
  {
    userAddress: "광주광역시 어디구 어디로",
    answerCount: null,
    couponNumber: "1132",
    imgStatus: true,
    name: "test",
    option: "전자책",
    userPhoneNumber: "010-4224-5678",
    questionCount: 2,
    userEmail: "dongheon9265@kakao.com",
    userId: 1630,
    userName: "재근",
    userNickname: "Heon",
    userSubscribeStory: 96,
    imgLink: "src/assets/images/testImg3.jpg",
    answers: [
      {
        people_answer:
          "항상 좋은 일만은 있을 순 없지요. 그럼에도 인생사 새옹지마 그런 일이 있어도 항상 나아가는 당신은 멋진 사람이에요",
        ai_answer:
          "여기에서 교훈을 얻을 수 있습니다. 운은 항상 준비된 자에게 오고 그걸 잡는건 당신의 준비성이라고. 그러므로 당신에게 행운을 빕니다.",
        etc: ["나는 행복합니다아아아.", "나는 아주아주  행복합니다."],
      },
    ],
  },
  {
    userAddress: "부산광역시 어디구 어디로",
    answerCount: 1,
    couponNumber: "1132",
    imgStatus: true,
    name: "test",
    option: "전자책",
    userPhoneNumber: "010-4331-5778",
    questionCount: null,
    userEmail: "dongheon9265@kakao.com",
    userId: 1631,
    userName: "재근",
    userNickname: "Heon",
    userSubscribeStory: 93,
  },
  {
    userAddress: "경기도 어디시 어디구 어디로",
    answerCount: 2,
    couponNumber: "1132",
    imgStatus: false,
    name: "test",
    option: "전자책",
    userPhoneNumber: "010-3334-5678",
    questionCount: 2,
    userEmail: "dongheon9265@kakao.com",
    userId: 1629,
    userName: "재근",
    userNickname: "Heon",
    userSubscribeStory: 92,
    imgLink: "src/assets/images/testImg1.jpg",
  },
  {
    userAddress: "울산광역시 어디구 어디로",
    answerCount: 1,
    couponNumber: "1132",
    imgStatus: false,
    name: "test",
    option: "전자책",
    userPhoneNumber: "010-4334-5998",
    questionCount: 2,
    userEmail: "dongheon9265@kakao.com",
    userId: 1628,
    userName: "재근",
    userNickname: "Heon",
    userSubscribeStory: 91,
  },
  {
    userAddress: "울산광역시 어디구 어디로",
    answerCount: 1,
    couponNumber: "1132",
    imgStatus: false,
    name: "test",
    option: "전자책",
    userPhoneNumber: "010-1334-5998",
    questionCount: 2,
    userEmail: "dongheon9265@kakao.com",
    userId: 1633,
    userName: "서재근",
    userNickname: "Heon",
    userSubscribeStory: 90,
  },
  {
    userAddress: "울산광역시 어디구 어디로",
    answerCount: 1,
    couponNumber: "1132",
    imgStatus: false,
    name: "test",
    option: "전자책",
    userPhoneNumber: "010-4324-5998",
    questionCount: 2,
    userEmail: "dongheon9265@kakao.com",
    userId: 1634,
    userName: "서근",
    userNickname: "Heon",
    userSubscribeStory: 89,
  },
  {
    userAddress: "울산광역시 어디구 어디로",
    answerCount: 1,
    couponNumber: "1132",
    imgStatus: false,
    name: "test",
    option: "전자책",
    userPhoneNumber: "010-4334-5988",
    questionCount: 2,
    userEmail: "dongheon9265@kakao.com",
    userId: 1635,
    userName: "재근",
    userNickname: "Heon",
    userSubscribeStory: 88,
  },
];
