export const BList = [
  // 아무 것도 아닐 때 green 모든 과정 완료 black
  // 표지 전자 업로드 2
  {
    address: "인천광역시 어디구 어디로",
    answerCount: 2,
    couponNumber: "1127",
    imgStatus: false,
    name: "당신의 감정을 담아내다",
    option: "실물책",
    phone: "010-1234-5678",
    questionCount: 7,
    userEmail: "heos2jin@gmail.com",
    userId: 1618,
    userName: "동헌김",
    userNickname: "1",
    userSubscribeStory: 53,
  },
  {
    address: "15811 경기도 군포시 금정로임 ㅋ",
    answerCount: 4,
    couponNumber: "1131",
    imgStatus: true,
    name: "당신의 감정을 담아내다",
    option: "실물책",
    phone: "010-4136-1005",
    questionCount: 7,
    userEmail: "dongheon9265@kakao.com",
    userId: 1636,
    userName: "김동헌",
    userNickname: "Heon",
    userSubscribeStory: 95,
  },
  {
    address: "서울시 어디구 어디로",
    answerCount: 6,
    couponNumber: "1132",
    imgStatus: false,
    name: "test",
    option: "전자책",
    phone: "010-1234-5666",
    questionCount: 14,
    userEmail: "dongheon9265@kakao.com",
    userId: 1632,
    userName: "서재",
    userNickname: "Heon",
    userSubscribeStory: 94,
  },
  {
    address: "광주광역시 어디구 어디로",
    answerCount: 1,
    couponNumber: "1132",
    imgStatus: false,
    name: "test",
    option: "전자책",
    phone: "010-4224-5678",
    questionCount: 2,
    userEmail: "dongheon9265@kakao.com",
    userId: 1630,
    userName: "재근",
    userNickname: "Heon",
    userSubscribeStory: 96,
  },
  {
    address: "부산광역시 어디구 어디로",
    answerCount: 1,
    couponNumber: "1132",
    imgStatus: false,
    name: "test",
    option: "전자책",
    phone: "010-4331-5778",
    questionCount: 2,
    userEmail: "dongheon9265@kakao.com",
    userId: 1631,
    userName: "재근",
    userNickname: "Heon",
    userSubscribeStory: 93,
  },
  {
    address: "경기도 어디시 어디구 어디로",
    answerCount: 1,
    couponNumber: "1132",
    imgStatus: false,
    name: "test",
    option: "전자책",
    phone: "010-3334-5678",
    questionCount: 2,
    userEmail: "dongheon9265@kakao.com",
    userId: 1629,
    userName: "재근",
    userNickname: "Heon",
    userSubscribeStory: 92,
  },
  {
    address: "울산광역시 어디구 어디로",
    answerCount: 1,
    couponNumber: "1132",
    imgStatus: false,
    name: "test",
    option: "전자책",
    phone: "010-4334-5998",
    questionCount: 2,
    userEmail: "dongheon9265@kakao.com",
    userId: 1628,
    userName: "재근",
    userNickname: "Heon",
    userSubscribeStory: 91,
  },
  {
    address: "울산광역시 어디구 어디로",
    answerCount: 1,
    couponNumber: "1132",
    imgStatus: false,
    name: "test",
    option: "전자책",
    phone: "010-1334-5998",
    questionCount: 2,
    userEmail: "dongheon9265@kakao.com",
    userId: 1633,
    userName: "서재근",
    userNickname: "Heon",
    userSubscribeStory: 90,
  },
  {
    address: "울산광역시 어디구 어디로",
    answerCount: 1,
    couponNumber: "1132",
    imgStatus: false,
    name: "test",
    option: "전자책",
    phone: "010-4324-5998",
    questionCount: 2,
    userEmail: "dongheon9265@kakao.com",
    userId: 1634,
    userName: "서근",
    userNickname: "Heon",
    userSubscribeStory: 89,
  },
  {
    address: "울산광역시 어디구 어디로",
    answerCount: 1,
    couponNumber: "1132",
    imgStatus: false,
    name: "test",
    option: "전자책",
    phone: "010-4334-5988",
    questionCount: 2,
    userEmail: "dongheon9265@kakao.com",
    userId: 1635,
    userName: "재근",
    userNickname: "Heon",
    userSubscribeStory: 88,
  },
];
